// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/DiagramArchitecture.tsx": () => import("../components/mockups/DiagramArchitecture.tsx"),
  "./components/mockups/DiagramCas.tsx": () => import("../components/mockups/DiagramCas.tsx"),
  "./components/mockups/DiagramClasses.tsx": () => import("../components/mockups/DiagramClasses.tsx"),
  "./components/mockups/DiagramER.tsx": () => import("../components/mockups/DiagramER.tsx"),
  "./components/mockups/DiagramSequence.tsx": () => import("../components/mockups/DiagramSequence.tsx")
};
