// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/DiagramActiviteAuth.tsx": () => import("../components/mockups/DiagramActiviteAuth.tsx"),
  "./components/mockups/DiagramActiviteDeliberation.tsx": () => import("../components/mockups/DiagramActiviteDeliberation.tsx"),
  "./components/mockups/DiagramActiviteInscription.tsx": () => import("../components/mockups/DiagramActiviteInscription.tsx"),
  "./components/mockups/DiagramActiviteNotes.tsx": () => import("../components/mockups/DiagramActiviteNotes.tsx"),
  "./components/mockups/DiagramArchitecture.tsx": () => import("../components/mockups/DiagramArchitecture.tsx"),
  "./components/mockups/DiagramCas.tsx": () => import("../components/mockups/DiagramCas.tsx"),
  "./components/mockups/DiagramCasAuth.tsx": () => import("../components/mockups/DiagramCasAuth.tsx"),
  "./components/mockups/DiagramCasDeliberation.tsx": () => import("../components/mockups/DiagramCasDeliberation.tsx"),
  "./components/mockups/DiagramCasEleves.tsx": () => import("../components/mockups/DiagramCasEleves.tsx"),
  "./components/mockups/DiagramCasNotes.tsx": () => import("../components/mockups/DiagramCasNotes.tsx"),
  "./components/mockups/DiagramCasPersonnel.tsx": () => import("../components/mockups/DiagramCasPersonnel.tsx"),
  "./components/mockups/DiagramClasses.tsx": () => import("../components/mockups/DiagramClasses.tsx"),
  "./components/mockups/DiagramClassesAcademique.tsx": () => import("../components/mockups/DiagramClassesAcademique.tsx"),
  "./components/mockups/DiagramClassesAuth.tsx": () => import("../components/mockups/DiagramClassesAuth.tsx"),
  "./components/mockups/DiagramComposant.tsx": () => import("../components/mockups/DiagramComposant.tsx"),
  "./components/mockups/DiagramER.tsx": () => import("../components/mockups/DiagramER.tsx"),
  "./components/mockups/DiagramEtatDeliberation.tsx": () => import("../components/mockups/DiagramEtatDeliberation.tsx"),
  "./components/mockups/DiagramEtatEtudiant.tsx": () => import("../components/mockups/DiagramEtatEtudiant.tsx"),
  "./components/mockups/DiagramEtatUtilisateur.tsx": () => import("../components/mockups/DiagramEtatUtilisateur.tsx"),
  "./components/mockups/DiagramPackage.tsx": () => import("../components/mockups/DiagramPackage.tsx"),
  "./components/mockups/DiagramSequence.tsx": () => import("../components/mockups/DiagramSequence.tsx")
};
